const companies=[
{name:'(주)엠서클 / 하이닥',label:'M CIRCLE · MEDICAL',desc:'의학 정보형·전문가 인터뷰형 콘텐츠. 이력서에 확인되는 롱폼 작업을 우선 배치합니다.',tone:'medical',items:[
['민감한 전립선 암 수술, 로봇으로 안전하게 할 수 있습니다','촬영 · 편집','https://www.youtube.com/watch?v=ONNxg5ozPZU&list=PLv7ZMVvCbMIrrfit6l42RYKdINBitZAOd&index=5&t'],['살을 빼는 간헐적 단식, 안 먹는 게 아니라 잘 먹어야 합니다','촬영 · 편집','https://www.youtube.com/watch?v=X7_JhaVq3TU&t'],['[명의 풀버전] 당뇨병, 혈당 스파이크 관리 이거면 충분합니다','촬영 · 편집',''],['피부 타입별로 꼭 필요한 제품과 순서 알려드립니다','촬영 · 편집',''],['심방세동 예방! 가정 혈압, 심전도 체크로 시작하세요!','촬영',''],['운동별 추천하는 착즙 레시피를 알려드릴게요!','촬영 · 편집',''],[null,'추가 롱폼 슬롯 · 07',''],[null,'추가 롱폼 슬롯 · 08','']]},
{name:'덴매거진 / DEN Magazine',label:'DEN MAGAZINE · INTERVIEW',desc:'인물의 메시지와 분위기를 살리는 인터뷰·매거진형 브랜디드 콘텐츠.',tone:'magazine',items:[
['분당서울대학교병원 비뇨의학과 이상철 교수 | 첨단 의료와 환자를 잇는 따뜻한 혁신가','촬영 · 편집','https://www.youtube.com/watch?v=3NhIFUovfhQ&t'],['죽음으로 삶을 그리는 화가 | 한국 현대미술 거장 안창홍 작가','촬영','https://www.youtube.com/watch?v=GPAFu57FTog'],['DEN MAGAZINE VIDEO 03','촬영 · 편집','https://www.youtube.com/watch?v=3HEUEPCQGOI'],['DEN MAGAZINE VIDEO 04','촬영 · 편집','https://www.youtube.com/watch?v=aLEkg0je-xQ'],['DEN MAGAZINE VIDEO 05','촬영 · 편집','https://www.youtube.com/watch?v=lae-_FXvepA&t'],['DEN MAGAZINE VIDEO 06','촬영 · 편집','https://www.youtube.com/watch?v=F61VLqyAhpU']]},
{name:'카123테크',label:'CAR123TECH · AUTOMOTIVE',desc:'자동차 정비 기반 정보형 콘텐츠. 현장 촬영, 편집, 플랫폼별 업로드 흐름까지 연결한 작업.',tone:'car',items:[
['명장님의 박살난 BMW 저희가 고쳐드렸습니다 | part 1','촬영 · 편집','https://www.youtube.com/watch?v=22GGFnOV1M8&t'],['1900년산 기아 세레스 이번에 입고되었습니다 ㅠㅠ','촬영 · 편집','https://www.youtube.com/watch?v=xni0p0FyI4w&t'],[null,'추가 롱폼 슬롯 · 03',''],[null,'추가 롱폼 슬롯 · 04',''],[null,'추가 롱폼 슬롯 · 05',''],[null,'추가 롱폼 슬롯 · 06','']]},
{name:'군집텍 / GOONZIPTEC',label:'GOONZIPTEC · DRONE',desc:'드론 교육 및 항공 촬영 기반 콘텐츠. 설명형 콘텐츠 편집과 현장 지원 경험을 보여주는 작업.',tone:'drone',items:[
['GOONZIPTEC VIDEO 01','편집','https://www.youtube.com/watch?v=Ypy3hjNoBPk&t'],['GOONZIPTEC VIDEO 02','편집','https://www.youtube.com/watch?v=xh52bXK0uvQ&t'],['GOONZIPTEC VIDEO 03','편집','https://www.youtube.com/watch?v=F-184RGSwLI'],['GOONZIPTEC VIDEO 04','편집','https://www.youtube.com/watch?v=vVue27dWUuk'],['[드론자격증] 드론1종 자격증 실기비행','편집',''],['[드론자격증] 드론 1종 자격증 실기비행 조종법 꿀팁','편집','']]},
{name:'SHORTS',label:'SHORTFORM · ALL CHANNELS',desc:'엠서클·덴매거진·카123테크의 숏폼을 한 곳에 모아 보여줍니다.',tone:'shorts',items:[
['엠서클 SHORTS 01','촬영 · 편집','https://www.youtube.com/shorts/q04ky6W7eMo'],['엠서클 SHORTS 02','촬영 · 편집','https://www.youtube.com/shorts/Djn4jOGuhDo'],['엠서클 SHORTS 03','촬영 · 편집','https://www.youtube.com/shorts/AfRa1CKFfAg'],['엠서클 SHORTS 04','촬영 · 편집','https://www.youtube.com/shorts/CmfJH00MtOQ'],['엠서클 SHORTS 05','촬영 · 편집','https://www.youtube.com/shorts/mLzx1RPvII4'],['덴매거진 SHORTS 01','촬영 · 편집','https://www.youtube.com/shorts/hojt0ATIorw'],['덴매거진 SHORTS 02','촬영 · 편집','https://www.youtube.com/shorts/N6LwgbUscz8'],['카123테크 SHORTS 01','촬영 · 편집','https://www.youtube.com/shorts/YT5W799NX5M'],['카123테크 SHORTS 02','촬영 · 편집','https://www.youtube.com/shorts/aasKCjwaJZU'],['카123테크 SHORTS 03','촬영 · 편집','https://www.youtube.com/shorts/nVBGVyZmd3U'],['카123테크 SHORTS 04','촬영 · 편집','https://www.youtube.com/shorts/RLHBL60JVCg'],['엠서클 SHORTS 06','촬영 · 편집','https://www.youtube.com/shorts/0zggdiRF9_E'],['엠서클 SHORTS 07','촬영 · 편집','https://www.youtube.com/shorts/JWSs5FVCRWQ'],['엠서클 SHORTS 08','촬영 · 편집','https://www.youtube.com/shorts/0mua6X2-Kb8'],['엠서클 SHORTS 09','촬영 · 편집','https://www.youtube.com/shorts/iFj8gITctyk'],['엠서클 SHORTS 10','촬영 · 편집','https://www.youtube.com/shorts/aZnoij_Md30'],['엠서클 SHORTS 11','촬영 · 편집','https://www.youtube.com/shorts/KmYqR26BS5U'],['엠서클 SHORTS 12','촬영 · 편집','https://www.youtube.com/shorts/nNDjaOB0380'],['엠서클 SHORTS 13','촬영 · 편집','https://www.youtube.com/shorts/aBnhgQ5D1Ts'],['엠서클 SHORTS 14','촬영 · 편집','https://www.youtube.com/shorts/xwwsg3o1uGE']]}
];
function getYoutubeId(url){if(!url)return'';try{const u=new URL(url);return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||''}catch{return''}}
const seenVideoIds=new Set();
companies.forEach(c=>{c.items=c.items.filter(it=>{const id=getYoutubeId(it[2]);if(!id)return true;if(seenVideoIds.has(id))return false;seenVideoIds.add(id);return true})});
const root=document.querySelector('#companies');
companies.forEach((c,ci)=>{const isShorts=ci===4;const sec=document.createElement('div');sec.className='company'+(isShorts?' shorts-company':'');sec.innerHTML=`<div class="company-top"><div><em>${String(ci+1).padStart(2,'0')} / ${c.label}</em><h3>${c.name}</h3><div class="company-desc">${c.desc}</div></div><div class="arrows"><button aria-label="이전 영상">←</button><button aria-label="다음 영상">→</button></div></div><div class="rail"></div>`;root.appendChild(sec);const rail=sec.querySelector('.rail');c.items.forEach((it,ii)=>{const id=getYoutubeId(it[2]);const card=document.createElement('article');card.className='card'+(id?' ready':' placeholder')+(isShorts?' short-card':'');card.innerHTML=`<div class="thumb tone-${c.tone}">${id?'<img loading="lazy" src="https://i.ytimg.com/vi/'+id+'/hqdefault.jpg" alt="'+(it[0]||'YouTube video')+'" /><span class="shade"></span><span class="play">▶</span>':''}</div><div class="info"><div class="meta"><span>${isShorts?(it[0]||'SHORTS').split(' ')[0]:c.label.split(' · ')[0]}</span><span>${String(ii+1).padStart(2,'0')}</span></div><div class="title">${it[0]||it[1]}</div><div class="role">${it[0]?it[1]:'영상 링크와 썸네일을 추가하면 이 카드가 활성화됩니다.'}</div></div>`;rail.appendChild(card);if(id)card.addEventListener('click',()=>{const liveTitle=card.querySelector('.title')?.textContent||it[0]||'YouTube video';openVideo(id,liveTitle,it[1],isShorts)});});const btns=sec.querySelectorAll('.arrows button');btns[0].onclick=()=>rail.scrollBy({left:-rail.clientWidth*.84,behavior:'smooth'});btns[1].onclick=()=>rail.scrollBy({left:rail.clientWidth*.84,behavior:'smooth'});});
async function loadActualTitles(){const tasks=[];companies.forEach(c=>c.items.forEach(it=>{const url=it[2],title=it[0];if(!url||!title||!/(?:VIDEO|SHORTS)\s+\d+$/i.test(title))return;tasks.push(fetch('https://www.youtube.com/oembed?url='+encodeURIComponent(url)+'&format=json').then(r=>r.ok?r.json():null).then(data=>{if(!data?.title)return;document.querySelectorAll('.title').forEach(el=>{if(el.textContent===title)el.textContent=data.title});it[0]=data.title}).catch(()=>{}))}));await Promise.allSettled(tasks)}
loadActualTitles();
const modal=document.querySelector('#modal'),player=document.querySelector('#player'),modalBox=document.querySelector('.modal-box');function openVideo(id,title,role,isShort){if(!id)return;modalBox.classList.toggle('short-video',!!isShort);player.innerHTML=`<iframe src="https://www.youtube.com/embed/${id}?autoplay=1&rel=0" title="${title}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;document.querySelector('#m-title').textContent=title;document.querySelector('#m-role').textContent=role;modal.classList.add('show');document.body.style.overflow='hidden'}function closeModal(){modal.classList.remove('show');modalBox.classList.remove('short-video');player.innerHTML='';document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
