const companies=[
{name:'(주)엠서클 / 하이닥',label:'M CIRCLE · MEDICAL',desc:'의학 정보형·전문가 인터뷰형 콘텐츠. 이력서에 확인되는 롱폼 작업을 우선 배치하고 추가 영상 슬롯을 남겨두었습니다.',tone:'medical',items:[
['민감한 전립선 암 수술, 로봇으로 안전하게 할 수 있습니다','촬영 · 편집',''],['살을 빼는 간헐적 단식, 안 먹는 게 아니라 잘 먹어야 합니다','촬영 · 편집',''],['[명의 풀버전] 당뇨병, 혈당 스파이크 관리 이거면 충분합니다','촬영 · 편집',''],['피부 타입별로 꼭 필요한 제품과 순서 알려드립니다','촬영 · 편집',''],['심방세동 예방! 가정 혈압, 심전도 체크로 시작하세요!','촬영',''],['운동별 추천하는 착즙 레시피를 알려드릴게요!','촬영',''],[null,'추가 롱폼 슬롯 · 07',''],[null,'추가 롱폼 슬롯 · 08','']]},
{name:'덴매거진 / DEN Magazine',label:'DEN MAGAZINE · INTERVIEW',desc:'인물의 메시지와 분위기를 살리는 인터뷰·매거진형 브랜디드 콘텐츠.',tone:'magazine',items:[
['분당서울대학교병원 비뇨의학과 이상철 교수 | 첨단 의료와 환자를 잇는 따뜻한 혁신가','촬영 · 편집',''],['죽음으로 삶을 그리는 화가 | 한국 현대미술 거장 안창홍 작가','촬영',''],[null,'추가 인터뷰 슬롯 · 03',''],[null,'추가 인터뷰 슬롯 · 04',''],[null,'추가 인터뷰 슬롯 · 05',''],[null,'추가 인터뷰 슬롯 · 06','']]},
{name:'카123테크',label:'CAR123TECH · AUTOMOTIVE',desc:'자동차 정비 기반 정보형 콘텐츠. 현장 촬영, 편집, 플랫폼별 업로드 흐름까지 연결한 작업.',tone:'car',items:[
['명장님의 박살난 BMW 저희가 고쳐드렸습니다 | part 1','촬영 · 편집',''],['1900년산 기아 세레스 이번에 입고되었습니다 ㅠㅠ','촬영 · 편집',''],[null,'추가 롱폼 슬롯 · 03',''],[null,'추가 롱폼 슬롯 · 04',''],[null,'추가 롱폼 슬롯 · 05',''],[null,'추가 롱폼 슬롯 · 06','']]},
{name:'군집텍 / GOONZIPTEC',label:'GOONZIPTEC · DRONE',desc:'드론 교육 및 항공 촬영 기반 콘텐츠. 설명형 콘텐츠 편집과 현장 지원 경험을 보여주는 작업.',tone:'drone',items:[
['[드론자격증] 드론1종 자격증 실기비행','편집',''],['[드론자격증] 드론 1종 자격증 실기비행 조종법 꿀팁','편집',''],[null,'추가 롱폼 슬롯 · 03',''],[null,'추가 롱폼 슬롯 · 04',''],[null,'추가 롱폼 슬롯 · 05',''],[null,'추가 롱폼 슬롯 · 06','']]},
{name:'SHORTS',label:'SHORTFORM · ALL CHANNELS',desc:'이력서에 명시된 Shorts 작업을 한 곳에 모아 보여줍니다. 추가 영상은 링크 입력만 하면 자동으로 늘릴 수 있습니다.',tone:'shorts',items:[
['타이밍벨트와 체인 차이점이 뭘까?','촬영 · 편집',''],['계단걷기 지금까지 잘못된 방법으로 걷고 있었다?','기획 · 편집',''],['항산화 영양소가 풍부한 고구마 빠스!','기획 · 편집',''],['입맛 없을 때 먹기 좋은 음식 3가지?','기획 · 편집',''],['신장이 망가질 때 나타나는 충격적인 5가지 증상!','기획 · 편집',''],['스쿼트보다 좋은 하체 운동? 이 운동 무조건 해보세요!','기획 · 편집',''],['하루 안에 목감기 낫는 방법 3가지!','기획 · 편집',''],['영양수액을 맞는 적당한 주기는?','촬영 · 편집',''],['이 영양제 꾸준히 먹으면 만성염증 해결?','촬영 · 편집',''],[null,'추가 Shorts 슬롯 · 10',''],[null,'추가 Shorts 슬롯 · 11',''],[null,'추가 Shorts 슬롯 · 12','']]}
];
const root=document.querySelector('#companies');
companies.forEach((c,ci)=>{const sec=document.createElement('div');sec.className='company';sec.innerHTML=`<div class="company-top"><div><em>${String(ci+1).padStart(2,'0')} / ${c.label}</em><h3>${c.name}</h3><div class="company-desc">${c.desc}</div></div><div class="arrows"><button aria-label="이전 영상">←</button><button aria-label="다음 영상">→</button></div></div><div class="rail"></div>`;root.appendChild(sec);const rail=sec.querySelector('.rail');c.items.forEach((it,ii)=>{const card=document.createElement('article');card.className='card'+(it[2]?' ready':' placeholder');card.innerHTML=`<div class="thumb tone-${c.tone}">${it[2]?'<span class="play">▶</span>':''}</div><div class="info"><div class="meta"><span>${ci===4?'SHORTS':c.label.split(' · ')[0]}</span><span>${String(ii+1).padStart(2,'0')}</span></div><div class="title">${it[0]||it[1]}</div><div class="role">${it[0]?it[1]:'영상 링크와 썸네일을 추가하면 이 카드가 활성화됩니다.'}</div></div>`;rail.appendChild(card);if(it[2])card.addEventListener('click',()=>openVideo(it[2],it[0],it[1]));});const btns=sec.querySelectorAll('.arrows button');btns[0].onclick=()=>rail.scrollBy({left:-rail.clientWidth*.84,behavior:'smooth'});btns[1].onclick=()=>rail.scrollBy({left:rail.clientWidth*.84,behavior:'smooth'});});
const modal=document.querySelector('#modal'),player=document.querySelector('#player');function openVideo(url,title,role){let id='';try{const u=new URL(url);id=u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||''}catch{}if(id==='shorts')id='';if(!id)return;player.innerHTML=`<iframe src="https://www.youtube.com/embed/${id}?autoplay=1&rel=0" title="${title}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;document.querySelector('#m-title').textContent=title;document.querySelector('#m-role').textContent=role;modal.classList.add('show');document.body.style.overflow='hidden'}function closeModal(){modal.classList.remove('show');player.innerHTML='';document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
