const companies=[
{name:'(주)엠서클 / 하이닥',label:'M CIRCLE · MEDICAL',desc:'의학 정보형·전문가 인터뷰형 콘텐츠. 이력서에 확인되는 롱폼 작업을 우선 배치합니다.',tone:'medical',items:[
['민감한 전립선 암 수술, 로봇으로 안전하게 할 수 있습니다','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=ONNxg5ozPZU&list=PLv7ZMVvCbMIrrfit6l42RYKdINBitZAOd&index=5&t'],['살을 빼는 간헐적 단식, 안 먹는 게 아니라 잘 먹어야 합니다','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=X7_JhaVq3TU&t'],['[명의 풀버전] 당뇨병, 혈당 스파이크 관리 이거면 충분합니다','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=Cqk2sq51-Ts&t=521s'],['피부 타입별로 꼭 필요한 제품과 순서 알려드립니다','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=PFoqroC7A6k&t=3s'],['심방세동 예방! 가정 혈압, 심전도 체크로 시작하세요!','메인 촬영','https://www.youtube.com/watch?v=XZC_p7t_Opg&t=5s'],['어떤 운동을 하시나요? 운동별 추천하는 착즙 레시피를 알려드릴게요!','서브 촬영','https://www.youtube.com/watch?v=_9N_8-R13sY']]},
{name:'덴매거진 / DEN Magazine',label:'DEN MAGAZINE · INTERVIEW',desc:'인물의 메시지와 분위기를 살리는 인터뷰·매거진형 브랜디드 콘텐츠.',tone:'magazine',items:[
['분당서울대학교병원 비뇨의학과 이상철 교수 | 첨단 의료와 환자를 잇는 따뜻한 혁신가','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=3NhIFUovfhQ&t'],['죽음으로 삶을 그리는 화가 | 한국 현대미술 거장 안창홍 작가','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=GPAFu57FTog'],['110만 닥터프렌즈 오진승 원장님이 말하는 \"어디서든 내 정체성은 정신과 의사다\"','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=3HEUEPCQGOI'],['극사실적 묘사로 사유의 공간을 마련하다 | 한국 극사실주의 이석주 작가','서브 촬영','https://www.youtube.com/watch?v=aLEkg0je-xQ'],['죽음으로 삶을 그리는 화가 | 한국 현대미술 거장 안창홍 작가','서브 촬영','https://www.youtube.com/watch?v=lae-_FXvepA&t'],['오재원의 오해와 편견#2 : 내가 코리안 특급을 싫어하는 진짜 이유','서브 촬영','https://www.youtube.com/watch?v=F61VLqyAhpU']]},
{name:'카123테크',label:'CAR123TECH · AUTOMOTIVE',desc:'자동차 정비 기반 정보형 콘텐츠. 현장 촬영, 편집, 플랫폼별 업로드 흐름까지 연결한 작업.',tone:'car',items:[
['명장님의 박살난 BMW 저희가 고쳐드렸습니다 | part 1','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=22GGFnOV1M8&t'],['1900년산 기아 세레스 이번에 입고되었습니다 ㅠㅠ','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=xni0p0FyI4w&t']]},
{name:'군집텍 / GOONZIPTEC',label:'GOONZIPTEC · DRONE',desc:'드론 교육 및 항공 촬영 기반 콘텐츠. 설명형 콘텐츠 편집과 현장 지원 경험을 보여주는 작업.',tone:'drone',items:[
['[드론자격증] 드론 1종 자격증 실기비행 조종법 꿀팁_Drone certificate','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=Ypy3hjNoBPk&t'],['드론1종자격증 실기비행','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=xh52bXK0uvQ&t'],['[드론자격증] 현직 교관이 알려주는 드론 자격증 및 취업! [certificate & job]','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=F-184RGSwLI'],['DJI 인스파이어2 사용법 PART1_DJI INSPIRE 2','메인 촬영 · 메인 편집','https://www.youtube.com/watch?v=vVue27dWUuk']]},
{name:'SHORTS',label:'SHORTFORM · ALL CHANNELS',desc:'엠서클·덴매거진·카123테크의 숏폼을 한 곳에 모아 보여줍니다.',tone:'shorts',items:[
['먹어도 살이 찌지 않는 만두가 있다? #shorts','메인 편집','https://www.youtube.com/shorts/q04ky6W7eMo'],['하루 안에 목감기 낫는 방법 3가지!','메인 편집','https://www.youtube.com/shorts/Djn4jOGuhDo'],['혈당 조절이 안 된다는 뜻은? #shorts','메인 편집','https://www.youtube.com/shorts/AfRa1CKFfAg'],['과학적으로 검증된 허리를 위한 장요근 스트레칭 #shorts','메인 편집','https://www.youtube.com/shorts/CmfJH00MtOQ'],['코로나 예방하는 UDCA #shorts','메인 편집','https://www.youtube.com/shorts/mLzx1RPvII4'],['캔으로 마신 기네스가 맛이 없는 이유?','메인 편집','https://www.youtube.com/shorts/hojt0ATIorw'],['지금 마시고 있는 기네스가 100억의 가치를 가지고 있다?','메인 편집','https://www.youtube.com/shorts/N6LwgbUscz8'],['타이밍벨트와 체인 차이점이 뭘까?','메인 편집','https://www.youtube.com/shorts/YT5W799NX5M'],['자동차 명장이 차를 BMW로 바꾼 이유','메인 편집','https://www.youtube.com/shorts/aasKCjwaJZU'],['독일 차는 확실히 이게 좋은 거 같다?','메인 편집','https://www.youtube.com/shorts/nVBGVyZmd3U'],['타이밍 체인, 벨트 교환 주기 딱 알려드립니다','메인 편집','https://www.youtube.com/shorts/RLHBL60JVCg'],['스쿼트보다 좋은 하체 운동? 이 \'운동\' 무조건 해보세요!','메인 편집','https://www.youtube.com/shorts/0zggdiRF9_E'],['목소리를 잃을 수도 있는 성대결절, 감기와 구별하는 방법은?','메인 편집','https://www.youtube.com/shorts/JWSs5FVCRWQ'],['쉬운 푸쉬업의 정석? 가장 완벽한 자세 알려드립니다!','메인 편집','https://www.youtube.com/shorts/0mua6X2-Kb8'],['영양수액을 맞는 적당한 주기는? #shorts','메인 편집','https://www.youtube.com/shorts/iFj8gITctyk'],['골반, 허리, 무릎 통증 없애는 내전근 스트레칭! #shorts','메인 편집','https://www.youtube.com/shorts/aZnoij_Md30'],['연속 혈당 측정기 착용 방법은? #shorts','메인 편집','https://www.youtube.com/shorts/KmYqR26BS5U'],['신장이 망가질 때 나타나는 충격적인 5가지 증상!','메인 편집','https://www.youtube.com/shorts/nNDjaOB0380'],['당뇨병 환자에게 위험한 이것?','메인 편집','https://www.youtube.com/shorts/aBnhgQ5D1Ts'],['세수하다 눈에 \'뭐\'가 들어가셨나요?...그럴 땐 \'이렇게\'!','메인 편집','https://www.youtube.com/shorts/xwwsg3o1uGE']]}
];
function getYoutubeId(url){if(!url)return'';try{const u=new URL(url);return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||''}catch{return''}}
const seenVideoIds=new Set();
companies.forEach(c=>{c.items=c.items.filter(it=>{const id=getYoutubeId(it[2]);if(!id)return true;if(seenVideoIds.has(id))return false;seenVideoIds.add(id);return true})});
const root=document.querySelector('#companies');
companies.forEach((c,ci)=>{const isShorts=ci===4;const sec=document.createElement('div');sec.className='company'+(isShorts?' shorts-company':'');sec.innerHTML=`<div class="company-top"><div><em>${String(ci+1).padStart(2,'0')} / ${c.label}</em><h3>${c.name}</h3><div class="company-desc">${c.desc}</div></div><div class="arrows"><button aria-label="이전 영상">←</button><button aria-label="다음 영상">→</button></div></div><div class="rail"></div>`;root.appendChild(sec);const rail=sec.querySelector('.rail');c.items.forEach((it,ii)=>{const id=getYoutubeId(it[2]);const card=document.createElement('article');card.className='card'+(id?' ready':' placeholder')+(isShorts?' short-card':'');if(id){card.dataset.videoId=id;card.dataset.placeholderTitle=it[0]||''}card.innerHTML=`<div class="thumb tone-${c.tone}">${id?'<img loading="lazy" src="https://i.ytimg.com/vi/'+id+'/hqdefault.jpg" alt="'+(it[0]||'YouTube video')+'" /><span class="play">▶</span>':''}</div><div class="info"><div class="meta"><span>${isShorts?(it[0]||'SHORTS').split(' ')[0]:c.label.split(' · ')[0]}</span><span>${String(ii+1).padStart(2,'0')}</span></div><div class="title">${it[0]||it[1]}</div><div class="role">${it[0]?it[1]:'영상 링크와 썸네일을 추가하면 이 카드가 활성화됩니다.'}</div></div>`;rail.appendChild(card);if(id){const img=card.querySelector('.thumb img');if(img)img.addEventListener('error',()=>{const step=img.dataset.fallback||'0';if(step==='0'){img.dataset.fallback='1';img.src='https://i.ytimg.com/vi/'+id+'/sddefault.jpg'}else if(step==='1'){img.dataset.fallback='2';img.src='https://img.youtube.com/vi/'+id+'/0.jpg'}});card.addEventListener('click',()=>{const liveTitle=card.querySelector('.title')?.textContent||it[0]||'YouTube video';openVideo(id,liveTitle,it[1],isShorts)})}});const btns=sec.querySelectorAll('.arrows button');btns[0].onclick=()=>rail.scrollBy({left:-rail.clientWidth*.84,behavior:'smooth'});btns[1].onclick=()=>rail.scrollBy({left:rail.clientWidth*.84,behavior:'smooth'});});
const modal=document.querySelector('#modal'),player=document.querySelector('#player'),modalBox=document.querySelector('.modal-box');function openVideo(id,title,role,isShort){if(!id)return;modalBox.classList.toggle('short-video',!!isShort);player.innerHTML=`<iframe src="https://www.youtube.com/embed/${id}?autoplay=1&rel=0" title="${title}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;document.querySelector('#m-title').textContent=title;document.querySelector('#m-role').textContent=role;modal.classList.add('show');document.body.style.overflow='hidden'}function closeModal(){modal.classList.remove('show');modalBox.classList.remove('short-video');player.innerHTML='';document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
